    -- Insertar canciones
INSERT INTO songs (title, duration) VALUES
    ('Smells Like Teen Spirit', 301),
    ('Bohemian Rhapsody', 355),
    ('Imagine', 183),
    ('Sweet Child o` Mine', 355),
    ('Hotel California', 390),
    ('Hey Jude', 431),
    ('Stairway to Heaven', 482),
    ('Like a Rolling Stone', 369),
    ('Wonderwall', 258),
    ('Yesterday', 124),
    ('Thriller', 357),
    ('Billie Jean', 294),
    ('Don`t Stop Believin`', 269),
    ('Let It Be', 240),
    ('Piano Man', 330),
    ('Smells Like Teen Spirit', 301),
    ('Bohemian Rhapsody', 355),
    ('Imagine', 183),
    ('Sweet Child o` Mine', 355),
    ('Hotel California', 390),
    ('Hey Jude', 431),
    ('Stairway to Heaven', 482),
    ('Like a Rolling Stone', 369),
    ('Wonderwall', 258),
    ('Yesterday', 124),
    ('Thriller', 357),
    ('Billie Jean', 294),
    ('Don`t Stop Believin`', 269),
    ('Let It Be', 240),
    ('Piano Man', 330),
    ('In the Stars', 214),
    ('Lost in Time', 185),
    ('Eternal Love', 312),
    ('Electric Dreams', 267),
    ('Rhythm of the Night', 240),
    ('Whispering Shadows', 192),
    ('Midnight Serenade', 313),
    ('Dancing Fireflies', 238),
    ('Rainy Day Melody', 182),
    ('Sunset Dreams', 289),
    ('The Enchanted Forest', 221),
    ('Silver Lining', 256),
    ('Mystic Journey', 301),
    ('Melancholy Memories', 197),
    ('Ocean Symphony', 288),
    ('Celestial Harmonies', 223),
    ('Dreamcatcher', 267),
    ('Serenade of Hope', 191),
    ('Magical Echoes', 315),
    ('Starlight Sonata', 248),
    ('Euphoric Bliss', 202),
    ('Whispers of Tomorrow', 275),
    ('Harmony`s Embrace', 223),
    ('Wandering Souls', 251),
    ('Golden Horizon', 299),
    ('Dance of Illusions', 210),
    ('Shimmering Sands', 286),
    ('Uncharted Destinations', 234),
    ('Symphony of Wonder', 269),
    ('Surreal Reverie', 217),
    ('Whispered Secrets', 246),
    ('Echoes of Infinity', 305),
    ('Luminescent Melodies', 231),
    ('Mystical Cascade', 283),
    ('Enigmatic Whispers', 196),
    ('Astral Journey', 303),
    ('Whirling Fantasia', 229),
    ('Tranquil Oasis', 266),
    ('Celestial Lullaby', 213),
    ('Dancing Aurora', 285),
    ('Velvet Moonlight', 240),
    ('Harmonic Elixir', 295),
    ('Enchanted Reverie', 225),
    ('Elysian Fields', 277),
    ('Cascading Stardust', 208),
    ('Whimsical Dreamland', 291),
    ('Timeless Reflections', 221),
    ('Melodic Whispers', 252),
    ('Mystic Echoes', 241),
    ('Dreamscape', 283),
    ('Whispering Breeze', 197),
    ('Celestial Rhapsody', 316),
    ('Serendipity', 235),
    ('Harmonic Fusion', 209),
    ('Ethereal Melodies', 274),
    ('Aurora`s Embrace', 229),
    ('Moonlit Serenade', 303),
    ('Enchanted Melancholy', 192),
    ('Twilight Reverie', 287),
    ('Crystal Symphony', 222),
    ('Serenity', 261),
    ('Whispering Moonlight', 212),
    ('Mystical Journey', 295),
    ('Harmony in Motion', 240),
    ('Whimsical Whispers', 202),
    ('Silent Echo', 267),
    ('Stellar Dreams', 201),
    ('Luminous Melody', 292),
    ('Tranquil Reflections', 219),
    ('Celestial Embrace', 254),
    ('Euphoria', 308),
    ('Whispering Willow', 223),
    ('Melody of Eternity', 297),
    ('Enchanted Journey', 236),
    ('Mystic Oasis', 272),
    ('Harmony`s End', 196),
    ('Serenade of Stars', 312),
    ('Aetherial Whispers', 215),
    ('Dreams of Tomorrow', 280),
    ('Twilight Symphony', 225),
    ('Whispering Harmony', 249),
    ('Enigmatic Serenade', 289),
    ('Radiant Melodies', 206),
    ('Dance of the Fireflies', 257),
    ('Celestial Escape', 240),
    ('Whimsical Dreamscape', 264),
    ('Elysian Whispers', 203),
    ('Moonlit Reverie', 282),
    ('Melancholic Serenity', 228),
    ('Stardust Melodies', 309),
    ('Tranquil Twilight', 219),
    ('Harmonic Echoes', 244),
    ('Mystical Enchantment', 297),
    ('Whispering Lullaby', 215),
    ('Celestial Journey', 295),
    ('Serenade of Dreams', 231),
    ('Ethereal Symphony', 282),
    ('Enchanted Reflections', 206),
    ('Whispered Melancholy', 268),
    ('Aurora`s Serenade', 228),
    ('Moonlight Waltz', 307),
    ('Lullaby of the Stars', 222),
    ('Harmony`s Legacy', 239),
    ('Mystic Whispers', 288),
    ('Dreamer`s Delight', 199),
    ('Whimsical Illusions', 273),
    ('Eternal Serenity', 213),
    ('Silent Symphony', 296),
    ('Tranquil Melodies', 218),
    ('Celestial Euphony', 247),
    ('Enchanted Twilight', 303),
    ('Melody of the Cosmos', 224),
    ('Whispering Zephyr', 258),
    ('Mystical Dreams', 291),
    ('Harmonic Solitude', 208),
    ('Serenade of Hope', 312),
    ('Elysian Echoes', 214),
    ('Moonlit Rhapsody', 301),
    ('Enchanted Overture', 239),
    ('Celestial Echo', 284),
    ('Whispering Cascade', 202),
    ('Dreams of Serenity', 277),
    ('Twilight Ballad', 233),
    ('Melancholic Whispers', 289),
    ('Stellar Symphony', 207),
    ('Tranquil Serenade', 298),
    ('Harmony`s Embrace', 225),
    ('Mystic Harmony', 295),
    ('Whispered Melodies', 215),
    ('Celestial Voyage', 300),
    ('Enchanted Illusions', 232),
    ('Moonlight Serenade', 293),
    ('Ethereal Reverie', 212),
    ('Serenade of Tranquility', 286),
    ('Astral Melodies', 218),
    ('Whimsical Reflections', 279),
    ('Melody of Dreams', 206);

   -- Verificar Tabla
   -- SELECT * FROM songs